language: 
 - cpp
 - objective-c

compiler: 
 - clang

cache: apt

before_install:
 - ./travis_before_install.sh

before_script:
 - mkdir BUILD
 - cd BUILD
 - cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt4/4.8.5 -DSC_QT=1 .. --debug-output

script: make

notifications:
 email:
   - scott@artificia.org
 on_success: always
 on_failure: always