compiler:
 - gcc

os:
 - linux
 - osx

cache: apt

before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - export COMMIT_NAME=`echo $TRAVIS_COMMIT | cut -c1-7`
 - ifmac brew update
 - ifmac brew install cmake qt5
 - iflin sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
 - iflin sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake  # backport of cmake 2.8.12
 - iflin sudo apt-get update
 - iflin sudo apt-get install gcc-4.7 g++-4.7 aptitude build-essential libjack-dev libsndfile1-dev libasound2-dev libavahi-client-dev libicu-dev libreadline6-dev libfftw3-dev libxt-dev libudev-dev pkg-config cmake=2.8.12.2-3 subversion libstdc++5 qtbase5-dev qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5webkit5-dev libudev-dev 
 - iflin sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6 
 - iflin sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7 
 - iflin sudo update-alternatives --auto gcc

before_script:
 - iflin aptitude why libqt4-dev
 - mkdir BUILD
 - cd BUILD
 - ifmac cmake -DCMAKE_PREFIX_PATH=`brew --prefix qt5` -DSC_QT=1 .. --debug-output
 - iflin cmake -DSC_EL=no -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt5/ -DCMAKE_INSTALL_PREFIX:PATH=$PWD/Install -DCMAKE_BUILD_TYPE=Release .. --debug-output

script:
 - make install

before_deploy:
 - git fetch --tags
 - export BUILD_PREFIX=$TRAVIS_REPO_SLUG/$TRAVIS_OS_NAME
 - export TAG_NAME=${TRAVIS_TAG:=head}
 - mkdir $HOME/artifacts
 - zip -r $HOME/artifacts/SC-$COMMIT_NAME.zip Install/
 - echo '<html><head><meta http-equiv="refresh" content="0; url=http://supercollider.s3.amazonaws.com/builds/'$BUILD_PREFIX/SC-$COMMIT_NAME.zip'" /></head></html>' > $HOME/artifacts/$TRAVIS_BRANCH-latest.html
 - echo '<html><head><meta http-equiv="refresh" content="0; url=http://supercollider.s3.amazonaws.com/builds/'$BUILD_PREFIX/SC-$COMMIT_NAME.zip'" /></head></html>' > $HOME/artifacts/$TAG_NAME.html

deploy:
 - provider: s3
   access_key_id: AKIAJJHRJG4Y6SVYKUKA
   secret_access_key:
     secure: jWZbN5Nmlbv1RNZgRRsb1gkTflzSGUXDJGUUgIaQR3zYYb/3K9vHoX25HPckbJ6djnAu5vWXyBuMKA4ftaHRzBkg/+9sNN3sJi4xLdM5TfCSpbazO1n5cuDlVJ0uXB0wsiwGWvYP7PiXnw0vlxe94mScuesExK6IbGCzFc14PIc=
   bucket: supercollider
   local-dir: $HOME/artifacts
   upload-dir: builds/$BUILD_PREFIX
   region: us-west-2
   skip_cleanup: true
   endpoint: s3-us-west-2.amazonaws.com
   acl: public_read
   on:
     condition: $TRAVIS_OS_NAME = osx
     repo: scztt/supercollider
 - provider: releases
   api_key:
     secure: K3X3Ja+j4iKwb6SOpxebV5acVBl5C8tXoTBWb3bO9iwJjYpzIYFi7Mr5zUIz/0hx8pgyr2eNrWEL/YOOyg7BzfPG7wiSfjDPpsPRYvx4XQslXOivsfljKy/rK4wN1edj5ZK7ydlygBaNkrlxH2JQDjTNvveYr+b6LHrD7N0mWqE=
   file: $HOME/artifacts/SC-$COMMIT_NAME.zip
   prerelease: true
   skip_cleanup: true
   on:
     condition: $TRAVIS_OS_NAME = osx
     repo: scztt/supercollider
     tags: true
     all_branches: true

notifications:
 email:
   - scott@artificia.org
 on_success: change
 on_failure: always
